### ISSUE TITLE
Node API fails to fetch address/output data

### ISSUE THREAD

**Issue by mstrewe** [iotaledger/goshimmer#818]
**Actual behavior:**

Faucet is not able to send token to a address. Nether cli-wallet nor web Dashboard Faucet

**Expected behavior:**

Faucet should send 1337 iotas to given address.

**System:**

1. Hetzner vps  CX21, 4GB Ram, SSD, 2 V-Cores, Goshimmer v0.3.0 (commit 5eb76348af48856ec44f7a2eecddbaa45055f70a) build from source

2. Hetzner vps CPX31, 8 GB Ram, SSD, 4 V-cores, Goshimmer v0.3.0 (commit 5eb76348af48856ec44f7a2eecddbaa45055f70a) build from source

**What I have tried:**

On System 1, which was running for 16 days I was not able to request funds. Then I restartet the node with fresh db. After sync I was not able to request funds. Not on Dashboard, not with cli-walltet

On System 2, I install goshimmer freshly. After sync I was not able to request funds. Not on Dashboard, not with cli-walltet.

No errors reportet by goshimmer. But addresses stays empty.

**Comment by lzpap** [comment]
@mstrewe can you share which address you are trying to request funds to?

**Comment by Dr-Electron** [comment]
`anEhVr7cBJiM36LLdwPrJZFFrBpF1sxq6e2o6YPwTiFV` should be one. I don't think anyone from the GoShimmer X-Team can find it. Only @mstrewe could find it once. But not anymore after deleting the db and a reboot.

**Comment by lzpap** [comment]
I can find it on my node. If you have msg `2N2DhXX2MK3KfApXSagKcsWH1x5BcwtvaogLgNXoKryyu5wUj3NzahusXn9Eam6Xu7XVquK2y8WUqorbREnsPeEN` after deleting and reboot, it should be the same issue as previously, the node fails to correctly fetch address/output information from its db.

**Comment by mstrewe** [comment]
@lzpap can you try it with a fresh syncet node?

**Comment by mstrewe** [comment]
And I am even not able to request funds to a new wallet address

**Comment by Dr-Electron** [comment]
@mstrewe You are not able to request funds, or your node simply doesn't fetch the address correctly?
Because that's what happend to my address. 
@lzpap But if this is the problem, why does it happen to so many new dbs? Because a lot of people got this problem after deleting their db.

**Comment by mstrewe** [comment]
The cli wallet does not request as well. When I list addresses there is nothing. But could be the"address not found" problem too

**Comment by mstrewe** [comment]
Xu5ixSb33HWTBvWRMNC3uFJiVfnBCzA8vo32kKt7w3ZS this is my test address

**Comment by Dr-Electron** [comment]
Yeah, that was exactly my problem. But i can see the Token from the faucet on my address if i search for the message id by @lzpap :
`2N2DhXX2MK3KfApXSagKcsWH1x5BcwtvaogLgNXoKryyu5wUj3NzahusXn9Eam6Xu7XVquK2y8WUqorbREnsPeEN `.
So it is quite likely the same problem. 
Is there some IF managed Node we can use in the meantime?

**Comment by lzpap** [comment]
@mstrewe do you see msg `2oDECksu3e19Rczqx5d1rptvnfURaXTNL1VQUKuHXbauPxDkqaFxA8qCw1F4yS13iwPBotzUVF7f1VKE9Bj4CyYY` on your node? You can't request funds for this address, as it has already been used, hence blacklisted. I presume it's the same issue.

**Comment by Dr-Electron** [comment]
@mstrewe  I checked on the node of @mstrewe. Same Problem. I can see the address theire with 1337 Token

**Comment by mstrewe** [comment]
![image](https://user-images.githubusercontent.com/15155589/97991074-3214c080-1de1-11eb-940a-d2c0cd5cae2e.png)
my node sees the message

**Comment by mstrewe** [comment]
![image](https://user-images.githubusercontent.com/15155589/97991149-51abe900-1de1-11eb-9889-728909f4daab.png)
but can not fetch the address

**Comment by stricki** [comment]
I can also confirm this issue. My two goshimmer nodes are now runing for 28 days (IDs: 9hGxZBS4dTM, DHiWucW5JSV). They work properly and are synced and they can also be used as entry nodes in the setting of the GUI pollen-wallet. So these two nodes' API work properly. 

![Screenshot from 2020-11-09 21-12-22](https://user-images.githubusercontent.com/17906700/98591839-1d4c9700-22d1-11eb-8161-967b706c8224.png)
![Screenshot from 2020-11-09 21-12-29](https://user-images.githubusercontent.com/17906700/98591856-23db0e80-22d1-11eb-8a82-9bdce6e86193.png)


However I have also installed 6 goshimmer nodes for community members and although these nodes report to be synced and also the live explorer shows all transactions, they do not work properly when used as entry node in the setting of the GUI pollen-wallet neither does the cli-wallet work on them. So there seems to be a problem of the web API for these nodes, but actually I cannot tell more, because I simply do not know where this issue comes from. Example IDs of the nodes are C5qFzbiV2Cw, MzsksAQrCPM or 8nAbDLXp54g.

![Screenshot from 2020-11-09 21-12-51](https://user-images.githubusercontent.com/17906700/98591890-33f2ee00-22d1-11eb-8b0c-0d76caab7624.png)
![Screenshot from 2020-11-09 21-12-56](https://user-images.githubusercontent.com/17906700/98591897-37867500-22d1-11eb-9f4d-bba84a625267.png)

**Comment by capossele** [comment]
We added some changes to hopefully "mitigate" this issue that will ship with the upcoming v0.3.1 release. 
We are also implementing substantial changes in the way the Tangle and transaction work (merging the message and the value Tangles together). That will definitively fix this issue, but it will require some more time to be completed.

**Comment by iamadamsiwy** [comment]
is this issue solved with 0.3.1? i am running into the same issues on differend nodes



![grafik](https://user-images.githubusercontent.com/61705488/101266082-1e47db80-374c-11eb-829a-7ad7ee72aad7.png)

![grafik](https://user-images.githubusercontent.com/61705488/101266093-2dc72480-374c-11eb-88d8-83389ddd2c55.png)

**Comment by capossele** [comment]
Unfortunately this issue is still present, and will most probably be until we will finish the merge of the message Tangle and the Value Tangle
